table vw_travel
	lineageTag: 7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d

	measure 'Total Spend' = SUM(vw_travel[amount_inr])
		formatString: ₹#,##0.00

	measure 'Total Spend INR' = SUM(vw_travel[amount_inr])
		formatString: ₹#,##0.00

	measure 'Total Completed Spend INR' = CALCULATE(SUM(vw_travel[amount_inr]), vw_travel[travelled_flag] = "Y")
		formatString: ₹#,##0.00

	measure 'Total Cancelled Spend INR' = CALCULATE(SUM(vw_travel[amount_inr]), vw_travel[travelled_flag] = "N")
		formatString: ₹#,##0.00

	measure 'Total Trips' = DISTINCTCOUNT(vw_travel[trip_id])
		formatString: #,##0

	measure 'Trips with Travelled Legs' = CALCULATE(DISTINCTCOUNT(vw_travel[trip_id]), vw_travel[travelled_flag] = "Y")
		formatString: #,##0

	measure 'Trips with Cancelled Legs' = CALCULATE(DISTINCTCOUNT(vw_travel[trip_id]), vw_travel[travelled_flag] = "N")
		formatString: #,##0

	measure 'Fully Flown Trips' = CALCULATE(DISTINCTCOUNT(vw_travel[trip_id]), FILTER(VALUES(vw_travel[trip_id]), CALCULATE(COUNTROWS(vw_travel), vw_travel[travelled_flag] = "N") = 0))
		formatString: #,##0

	measure 'Fully Cancelled Trips' = CALCULATE(DISTINCTCOUNT(vw_travel[trip_id]), FILTER(VALUES(vw_travel[trip_id]), CALCULATE(COUNTROWS(vw_travel), vw_travel[travelled_flag] = "Y") = 0))
		formatString: #,##0

	measure 'Partially Cancelled Trips' = CALCULATE(DISTINCTCOUNT(vw_travel[trip_id]), FILTER(VALUES(vw_travel[trip_id]), CALCULATE(COUNTROWS(vw_travel), vw_travel[travelled_flag] = "Y") > 0 && CALCULATE(COUNTROWS(vw_travel), vw_travel[travelled_flag] = "N") > 0))
		formatString: #,##0

	measure 'Total Tickets' = COUNTROWS(vw_travel)
		formatString: #,##0

	measure 'Completed Travel Tickets' = CALCULATE(COUNTROWS(vw_travel), vw_travel[travelled_flag] = "Y")
		formatString: #,##0

	measure 'Cancelled or Refunded Tickets' = CALCULATE(COUNTROWS(vw_travel), vw_travel[travelled_flag] = "N")
		formatString: #,##0

	measure 'Trips by Month' = DISTINCTCOUNT(vw_travel[trip_id])
		formatString: #,##0

	measure 'Trips by Business Group' = DISTINCTCOUNT(vw_travel[trip_id])
		formatString: #,##0

	measure 'Trips by Travel Summary' = DISTINCTCOUNT(vw_travel[trip_id])
		formatString: #,##0

	measure 'Spend by Business Group' = SUM(vw_travel[amount_inr])
		formatString: ₹#,##0.00

	measure 'Avg Spend per Trip' = DIVIDE([Total Completed Spend INR], [Trips with Travelled Legs], 0)
		formatString: ₹#,##0.00

	measure 'Policy Compliance Rate' = DIVIDE(CALCULATE(COUNTROWS(vw_travel), vw_travel[policy_compliance_status] = "COMPLIANT"), COUNTROWS(vw_travel), 0)
		formatString: 0.0%

	measure 'Policy Exceptions Count' = CALCULATE(COUNTROWS(vw_travel), vw_travel[policy_compliance_status] <> "COMPLIANT")
		formatString: #,##0

	column ticket_id
		dataType: string
		sourceColumn: ticket_id

	column trip_id
		dataType: string
		sourceColumn: trip_id

	column batch_id
		dataType: string
		sourceColumn: batch_id

	column employee_id
		dataType: string
		sourceColumn: employee_id

	column employee_name
		dataType: string
		sourceColumn: employee_name

	column business_unit
		dataType: string
		sourceColumn: business_unit

	column business_group
		dataType: string
		sourceColumn: business_group

	column department
		dataType: string
		sourceColumn: department

	column issue_date
		dataType: string
		sourceColumn: issue_date

	column travel_date
		dataType: string
		sourceColumn: travel_date

	column return_date
		dataType: string
		sourceColumn: return_date

	column origin_city
		dataType: string
		sourceColumn: origin_city

	column origin_country
		dataType: string
		sourceColumn: origin_country

	column dest_city
		dataType: string
		sourceColumn: dest_city

	column dest_country
		dataType: string
		sourceColumn: dest_country

	column origin_iso
		dataType: string
		sourceColumn: origin_iso

	column dest_iso
		dataType: string
		sourceColumn: dest_iso

	column ticket_status
		dataType: string
		sourceColumn: ticket_status

	column amount_original
		dataType: double
		sourceColumn: amount_original
		formatString: #,##0.00

	column currency
		dataType: string
		sourceColumn: currency

	column fx_rate
		dataType: double
		sourceColumn: fx_rate
		formatString: #,##0.0000

	column amount_inr
		dataType: double
		sourceColumn: amount_inr
		formatString: ₹#,##0.00

	column fx_rate_date
		dataType: string
		sourceColumn: fx_rate_date

	column fx_source
		dataType: string
		sourceColumn: fx_source

	column booking_channel
		dataType: string
		sourceColumn: booking_channel

	column cabin_class
		dataType: string
		sourceColumn: cabin_class

	column travelled_flag
		dataType: string
		sourceColumn: travelled_flag

	column trip_classification
		dataType: string
		sourceColumn: trip_classification

	column travel_summary
		dataType: string
		sourceColumn: travel_summary

	column policy_compliance_status
		dataType: string
		sourceColumn: policy_compliance_status

	column policy_violation_reason
		dataType: string
		sourceColumn: policy_violation_reason

	column approval_status
		dataType: string
		sourceColumn: approval_status

	column rejection_reason
		dataType: string
		sourceColumn: rejection_reason

	column override_applied
		dataType: int64
		sourceColumn: override_applied

	column record_hash
		dataType: string
		sourceColumn: record_hash

	column source_file
		dataType: string
		sourceColumn: source_file

	column updated_at
		dataType: string
		sourceColumn: updated_at

	partition vw_travel = m
		mode: import
		source =
			let
			    Source = PostgreSQL.Database("localhost:5432", "travel_warehouse"),
			    public_vw_travel = Source{[Schema="public",Item="vw_travel"]}[Data],
			    #"Changed Type" = Table.TransformColumnTypes(public_vw_travel,{
			        {"ticket_id", type text}, {"trip_id", type text}, {"batch_id", type text}, {"employee_id", type text},
			        {"employee_name", type text}, {"business_unit", type text}, {"business_group", type text}, {"department", type text},
			        {"issue_date", type date}, {"travel_date", type date}, {"return_date", type date},
			        {"origin_city", type text}, {"origin_country", type text}, {"dest_city", type text}, {"dest_country", type text},
			        {"origin_iso", type text}, {"dest_iso", type text}, {"ticket_status", type text},
			        {"amount_original", type number}, {"currency", type text}, {"fx_rate", type number}, {"amount_inr", type number},
			        {"fx_rate_date", type date}, {"fx_source", type text}, {"booking_channel", type text}, {"cabin_class", type text},
			        {"travelled_flag", type text}, {"trip_classification", type text}, {"travel_summary", type text},
			        {"policy_compliance_status", type text}, {"policy_violation_reason", type text},
			        {"approval_status", type text}, {"rejection_reason", type text}, {"override_applied", Int64.Type},
			        {"record_hash", type text}, {"source_file", type text}, {"updated_at", type datetime}
			    })
			in
			    #"Changed Type"
