"""Initial production schema with fixed-precision financial types, constraints, and audit tables

Revision ID: 546a7b0e7c2e
Revises: 
Create Date: 2026-10-01 00:27:21.616985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546a7b0e7c2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cleansed_tickets', 'amount_original',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('cleansed_tickets', 'fx_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('cleansed_tickets', 'amount_inr',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('cleansed_tickets', 'original_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('employee_master', 'quarterly_allowance_inr',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('fact_travel_tickets', 'amount_original',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('fact_travel_tickets', 'fx_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('fact_travel_tickets', 'amount_inr',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('fx_rates', 'rate_to_inr',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('staging_tickets', 'amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staging_tickets', 'amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('fx_rates', 'rate_to_inr',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('fact_travel_tickets', 'amount_inr',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('fact_travel_tickets', 'fx_rate',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('fact_travel_tickets', 'amount_original',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('employee_master', 'quarterly_allowance_inr',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('cleansed_tickets', 'original_amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('cleansed_tickets', 'amount_inr',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('cleansed_tickets', 'fx_rate',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('cleansed_tickets', 'amount_original',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
